export const BTN_ACTIONS = [
  { label: "AC", type: "clear", variant: "btn-gray" },
  { label: "DEL", type: "action", variant: "btn-orange" },
  { label: "+/-", type: "action", variant: "btn-gray" },
  { label: "%", type: "action", variant: "btn-gray" },
  { label: "÷", value: "/", type: "operator", variant: "btn-gray" },
  { label: "7", type: "number", variant: "btn-white" },
  { label: "8", type: "number", variant: "btn-white" },
  { label: "9", type: "number", variant: "btn-white" },
  { label: "×", value: "*", type: "operator", variant: "btn-gray" },
  { label: "4", type: "number", variant: "btn-white" },
  { label: "5", type: "number", variant: "btn-white" },
  { label: "6", type: "number", variant: "btn-white" },
  { label: "-", type: "operator", variant: "btn-gray" },
  { label: "1", type: "number", variant: "btn-white" },
  { label: "2", type: "number", variant: "btn-white" },
  { label: "3", type: "number", variant: "btn-white" },
  { label: "+", type: "operator", variant: "btn-gray" },
  { label: "0", type: "number", variant: "btn-white" },
  { label: ".", type: "number", variant: "btn-white" },
  { label: "=", type: "calculate", variant: "btn-orange" },
];
